### ISSUE TITLE
Fail to start Jupyter hub 

### ISSUE THREAD

**Issue by sheogorath15** [forschungsprojekte-II-ws2223/jupyterhub-gradeservice#3]
**Problem**: jupyterhub container keeps restarting

**Jupyterhub Log**

[I 2023-03-29 11:30:04.436 JupyterHub app:2810] Running JupyterHub version 3.1.1
[I 2023-03-29 11:30:04.436 JupyterHub app:2840] Using Authenticator: jwtauthenticator.jwtauthenticator.JSONWebTokenLocalAuthenticator
[I 2023-03-29 11:30:04.436 JupyterHub app:2840] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-12.1.0
[I 2023-03-29 11:30:04.436 JupyterHub app:2840] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-3.1.1
[I 2023-03-29 11:30:04.446 JupyterHub app:1694] Writing cookie_secret to /data/jupyterhub_cookie_secret
[E 2023-03-29 11:30:04.456 JupyterHub app:1828] Failed to connect to db: postgresql://postgres:[redacted]@hub-db:None/jupyterhub
[C 2023-03-29 11:30:04.456 JupyterHub app:1832] If you recently upgraded JupyterHub, try running
        jupyterhub upgrade-db
    to upgrade your JupyterHub database schema

**Jupyterhub DB Log**
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2023-03-29 11:30:04.581 UTC [36] LOG:  starting PostgreSQL 15.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-03-29 11:30:04.582 UTC [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-03-29 11:30:04.585 UTC [39] LOG:  database system was shut down at 2023-03-29 11:30:04 UTC
2023-03-29 11:30:04.588 UTC [36] LOG:  database system is ready to accept connections
sh: locale: not found
2023-03-29 11:30:04.213 UTC [30] WARNING:  no usable system locales were found
initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
2023-03-29 11:30:04.839 UTC [1] LOG:  starting PostgreSQL 15.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-03-29 11:30:04.839 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-03-29 11:30:04.839 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-03-29 11:30:04.841 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-03-29 11:30:04.845 UTC [52] LOG:  database system was shut down at 2023-03-29 11:30:04 UTC
2023-03-29 11:30:04.849 UTC [1] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2023-03-29 11:30:04.722 UTC [36] LOG:  received fast shutdown request
2023-03-29 11:30:04.723 UTC [36] LOG:  aborting any active transactions
2023-03-29 11:30:04.725 UTC [36] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
2023-03-29 11:30:04.727 UTC [37] LOG:  shutting down
2023-03-29 11:30:04.727 UTC [37] LOG:  checkpoint starting: shutdown immediate
2023-03-29 11:30:04.758 UTC [37] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.017 s, sync=0.013 s, total=0.032 s; sync files=250, longest=0.004 s, average=0.001 s; distance=4222 kB, estimate=4222 kB
2023-03-29 11:30:04.769 UTC [36] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

**Comment by lorddort** [comment]
hey we are investigating this issue.
for us, there was no problem with starting up jupyterhub.
Can you maybe write down the steps so we can reproduce the problem?

**Comment by sheogorath15** [comment]
Sure:

1. Cloning the repo
2. `docker build ./jupyterhub_docker/jupyterlab -t jupyterlab`
3. `cd jupyterhub_docker`
4.  `docker compose up -d --build`

**Comment by sheogorath15** [comment]
Going through the logs one more time, this line looks suspicious: 
`jupyterhub | [E 2023-03-31 11:50:35.868 JupyterHub app:1828] Failed to connect to db: postgresql://postgres:[redacted]@hub-db:None/jupyterhub`

**Comment by sheogorath15** [comment]
Is it possible that the environment variables have to be sourced first?

**Comment by sheogorath15** [comment]
If I inspect the Postgres container, I can at least see the jupyterhub table:
<img width="846" alt="Bildschirmfoto 2023-03-31 um 14 12 13" src="https://user-images.githubusercontent.com/48446789/229116998-d2a69592-d757-4bd9-acc8-a281095cc206.png">

**Comment by lorddort** [comment]
It seems that I cannot recreate this problem.
I've heard that some people from the team also encountered this problem in the past.
Their solution was just to delete everything they had on the project and clone this repo again.
So maybe try this or you can just delete image and volume of JupyterHub and run the given commands again?

**Comment by lorddort** [comment]
Otherwise the error must be in the docker compose file imo
but I think you didn't do any changes there

**Comment by lorddort** [comment]
> Going through the logs one more time, this line looks suspicious: `jupyterhub | [E 2023-03-31 11:50:35.868 JupyterHub app:1828] Failed to connect to db: postgresql://postgres:[redacted]@hub-db:None/jupyterhub`

Yeah your absolutely right. The problem is that JupyterHub is not connecting to DB
It should look like that if it is working
![image](https://user-images.githubusercontent.com/39204509/229259473-fd8e8ea2-908a-4aae-87d2-eb9d98aac5cc.png)

**Comment by maxschuele** [comment]
> **Problem**: jupyterhub container keeps restarting
> 
> **Jupyterhub Log**
> 
> [I 2023-03-29 11:30:04.436 JupyterHub app:2810] Running JupyterHub version 3.1.1 [I 2023-03-29 11:30:04.436 JupyterHub app:2840] Using Authenticator: jwtauthenticator.jwtauthenticator.JSONWebTokenLocalAuthenticator [I 2023-03-29 11:30:04.436 JupyterHub app:2840] Using Spawner: dockerspawner.dockerspawner.DockerSpawner-12.1.0 [I 2023-03-29 11:30:04.436 JupyterHub app:2840] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-3.1.1 [I 2023-03-29 11:30:04.446 JupyterHub app:1694] Writing cookie_secret to /data/jupyterhub_cookie_secret [E 2023-03-29 11:30:04.456 JupyterHub app:1828] Failed to connect to db: postgresql://postgres:[redacted]@hub-db:None/jupyterhub [C 2023-03-29 11:30:04.456 JupyterHub app:1832] If you recently upgraded JupyterHub, try running jupyterhub upgrade-db to upgrade your JupyterHub database schema
> 
> **Jupyterhub DB Log** The files belonging to this database system will be owned by user "postgres". This user must also own the server process.
> 
> The database cluster will be initialized with locale "en_US.utf8". The default database encoding has accordingly been set to "UTF8". The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> fixing permissions on existing directory /var/lib/postgresql/data ... ok creating subdirectories ... ok selecting dynamic shared memory implementation ... posix selecting default max_connections ... 100 selecting default shared_buffers ... 128MB selecting default time zone ... UTC creating configuration files ... ok running bootstrap script ... ok performing post-bootstrap initialization ... ok syncing data to disk ... ok
> 
> Success. You can now start the database server using:
> 
> ```
> pg_ctl -D /var/lib/postgresql/data -l logfile start
> ```
> 
> waiting for server to start....2023-03-29 11:30:04.581 UTC [36] LOG: starting PostgreSQL 15.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit 2023-03-29 11:30:04.582 UTC [36] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" 2023-03-29 11:30:04.585 UTC [39] LOG: database system was shut down at 2023-03-29 11:30:04 UTC 2023-03-29 11:30:04.588 UTC [36] LOG: database system is ready to accept connections sh: locale: not found 2023-03-29 11:30:04.213 UTC [30] WARNING: no usable system locales were found initdb: warning: enabling "trust" authentication for local connections initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb. 2023-03-29 11:30:04.839 UTC [1] LOG: starting PostgreSQL 15.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit 2023-03-29 11:30:04.839 UTC [1] LOG: listening on IPv4 address "0.0.0.0", port 5432 2023-03-29 11:30:04.839 UTC [1] LOG: listening on IPv6 address "::", port 5432 2023-03-29 11:30:04.841 UTC [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432" 2023-03-29 11:30:04.845 UTC [52] LOG: database system was shut down at 2023-03-29 11:30:04 UTC 2023-03-29 11:30:04.849 UTC [1] LOG: database system is ready to accept connections done server started CREATE DATABASE
> 
> /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
> 
> waiting for server to shut down....2023-03-29 11:30:04.722 UTC [36] LOG: received fast shutdown request 2023-03-29 11:30:04.723 UTC [36] LOG: aborting any active transactions 2023-03-29 11:30:04.725 UTC [36] LOG: background worker "logical replication launcher" (PID 42) exited with exit code 1 2023-03-29 11:30:04.727 UTC [37] LOG: shutting down 2023-03-29 11:30:04.727 UTC [37] LOG: checkpoint starting: shutdown immediate 2023-03-29 11:30:04.758 UTC [37] LOG: checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.017 s, sync=0.013 s, total=0.032 s; sync files=250, longest=0.004 s, average=0.001 s; distance=4222 kB, estimate=4222 kB 2023-03-29 11:30:04.769 UTC [36] LOG: database system is shut down done server stopped
> 
> PostgreSQL init process complete; ready for start up.

@sheogorath15 The logs you posted are only from the jupyterhub-db container and look fine to me (looks the same on my machine where it is working). Could you post the logs from the jupyterhub container as well? I think the issue is probably not related to the database connection.

**Comment by sheogorath15** [comment]
Thanks for looking into this. @maxschuele the first post should contain both logs; the Jupyter log is under the section **Jupyterhub Log**, the database log under **Jupyterhub DB Log**

**Comment by sheogorath15** [comment]
Great news: it works now! What fixed it for me was re-installing docker itself
